name: Build and Release

on:
  push:
    branches:
      - master
    paths:
      - "package.json"
  pull_request:
    branches:
      - master
    paths:
      - "package.json"
  workflow_dispatch:  # 添加这一行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "master"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm config set registry https://registry.npmmirror.com
          pnpm i --no-frozen-lockfile
      - name: Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          echo "VITE_API_URL is: $VITE_API_URL"
          pnpm build
      - name: zip
        run: |
          zip -r dist.zip dist
      - id: tag
        name: Generate release tag
        run: |
          SUB_STORE_RELEASE=`node --eval="process.stdout.write(require('./package.json').version)"`
          echo "release_tag=$SUB_STORE_RELEASE" >> $GITHUB_OUTPUT
      - name: Prepare release
        run: |
          pnpm i -D conventional-changelog-cli
          pnpm run changelog
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ./CHANGELOG.md
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Release ${{ steps.tag.outputs.release_tag }} - ${{ steps.date.outputs.date }}
          files: |
            dist.zip
